#!/usr/bin/env python

import sys

from chronos_rqt.timeline_module import ChronosRqt
from rqt_gui.main import Main

plugin = 'chronos_rqt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))