#!/usr/bin/env python

import sys

from scrollable_timeline.timeline_module import ScrollableTimeline
from rqt_gui.main import Main

plugin = 'scrollable_timeline'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))